---
extends: default

rules:
  line-length:
    max: 120
    level: warning
  indentation:
    spaces: 2
    indent-sequences: whatever
  comments:
    min-spaces-from-content: 1
  comments-indentation: {}
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']
  document-start: disable
  braces:
    max-spaces-inside: 1

ignore: |
  .pixi/
  build/
  .git/
  node_modules/
  tests/fixtures/invalid/
