"""Metrics module for statistical calculations, grading, and aggregation.

This module provides statistical functions, grading calculations,
run aggregation, process metrics, token tracking, ablation analysis,
and latency tracking for analyzing evaluation results across multiple runs.
"""

from scylla.metrics.ablation import (
    AblationResult,
    AblationStudy,
    ComponentRole,
    analyze_component,
    calculate_ablation_score,
    calculate_relative_impact,
    compare_tier_ablations,
    run_ablation_study,
)
from scylla.metrics.aggregator import (
    AggregatedStats,
    CrossTierAnalysis,
    MetricsRunResult,
    RunAggregator,
    TierStatistics,
)
from scylla.metrics.cross_tier import (
    CrossTierAnalyzer,
    PromptSensitivityAnalysis,
    TierTransitionAssessment,
    TierUplift,
    calculate_frontier_cop,
)
from scylla.metrics.grading import (
    DEFAULT_PASS_THRESHOLD,
    GradingResult,
    assign_letter_grade,
    calculate_composite_score,
    calculate_cost_delta,
    calculate_cost_of_pass,
    calculate_impl_rate,
    calculate_pass_rate,
    calculate_tier_uplift,
    grade_run,
)
from scylla.metrics.latency import (
    LatencyBreakdown,
    LatencyPhase,
    LatencyTracker,
    PhaseLatency,
    analyze_verification_overhead,
    calculate_latency_stats,
)
from scylla.metrics.process import (
    ChangeResult,
    ProcessMetrics,
    ProgressStep,
    ProgressTracker,
    calculate_cfp,
    calculate_cfp_simple,
    calculate_pr_revert_rate,
    calculate_pr_revert_rate_simple,
    calculate_process_metrics,
    calculate_process_metrics_simple,
    calculate_r_prog,
    calculate_r_prog_simple,
    calculate_strategic_drift,
    calculate_strategic_drift_simple,
)
from scylla.metrics.statistics import (
    Statistics,
    calculate_all,
    calculate_consistency,
    calculate_mean,
    calculate_median,
    calculate_mode,
    calculate_range,
    calculate_std_dev,
    calculate_variance,
)
from scylla.metrics.token_tracking import (
    ComponentCost,
    ComponentType,
    TierTokenAnalysis,
    TokenDistribution,
    TokenTracker,
    TokenUsage,
    analyze_tier_tokens,
    calculate_token_efficiency_ratio,
    compare_t2_t3_efficiency,
)

__all__ = [
    # Ablation
    "AblationResult",
    "AblationStudy",
    "ComponentRole",
    "analyze_component",
    "calculate_ablation_score",
    "calculate_relative_impact",
    "compare_tier_ablations",
    "run_ablation_study",
    # Aggregator
    "AggregatedStats",
    "CrossTierAnalysis",
    "MetricsRunResult",
    "RunAggregator",
    "TierStatistics",
    # Cross-tier analysis
    "CrossTierAnalyzer",
    "PromptSensitivityAnalysis",
    "TierTransitionAssessment",
    "TierUplift",
    "calculate_frontier_cop",
    # Grading
    "DEFAULT_PASS_THRESHOLD",
    "GradingResult",
    "assign_letter_grade",
    "calculate_composite_score",
    "calculate_cost_delta",
    "calculate_cost_of_pass",
    "calculate_impl_rate",
    "calculate_pass_rate",
    "calculate_tier_uplift",
    "grade_run",
    # Latency
    "LatencyBreakdown",
    "LatencyPhase",
    "LatencyTracker",
    "PhaseLatency",
    "analyze_verification_overhead",
    "calculate_latency_stats",
    # Process metrics
    "ChangeResult",
    "ProcessMetrics",
    "ProgressStep",
    "ProgressTracker",
    "calculate_cfp",
    "calculate_cfp_simple",
    "calculate_pr_revert_rate",
    "calculate_pr_revert_rate_simple",
    "calculate_process_metrics",
    "calculate_process_metrics_simple",
    "calculate_r_prog",
    "calculate_r_prog_simple",
    "calculate_strategic_drift",
    "calculate_strategic_drift_simple",
    # Statistics
    "Statistics",
    "calculate_all",
    "calculate_consistency",
    "calculate_mean",
    "calculate_median",
    "calculate_mode",
    "calculate_range",
    "calculate_std_dev",
    "calculate_variance",
    # Token tracking
    "ComponentCost",
    "ComponentType",
    "TierTokenAnalysis",
    "TokenDistribution",
    "TokenTracker",
    "TokenUsage",
    "analyze_tier_tokens",
    "calculate_token_efficiency_ratio",
    "compare_t2_t3_efficiency",
]
