name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible.

  - type: textarea
    id: objective
    attributes:
      label: Objective
      description: Brief description of what you want to achieve (2-3 sentences)
      placeholder: I would like to...
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature needed? What problem does it solve?
      placeholder: This would help by...
    validations:
      required: true

  - type: textarea
    id: deliverables
    attributes:
      label: Proposed Deliverables
      description: What should be delivered? (Use checkboxes if multiple)
      placeholder: |
        - [ ] Deliverable 1
        - [ ] Deliverable 2
      render: markdown
    validations:
      required: false

  - type: textarea
    id: success-criteria
    attributes:
      label: Success Criteria
      description: How will we know this feature is complete and working?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
      render: markdown
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions or features have you considered?
      placeholder: I also considered...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, mockups, or examples
      placeholder: Screenshots, related issues, etc.
    validations:
      required: false
