#!/usr/bin/env python3
"""Check test coverage against threshold.

This script validates that code coverage meets the required threshold.
Used in CI to enforce coverage requirements.

Usage:
    python scripts/check_coverage.py --threshold 90 --path scylla/
    python scripts/check_coverage.py --config coverage.toml --path scylla/metrics
"""

import argparse
import sys
from pathlib import Path

# Enable importing from repository root and scripts directory
_SCRIPT_DIR = Path(__file__).parent
_REPO_ROOT = _SCRIPT_DIR.parent
sys.path.insert(0, str(_REPO_ROOT))
sys.path.insert(0, str(_SCRIPT_DIR))

from common import get_repo_root  # noqa: E402

try:
    import tomllib
except ImportError:
    import tomli as tomllib  # type: ignore


def load_coverage_config(config_file: Path | None = None) -> dict:
    """Load coverage configuration from coverage.toml.

    Args:
        config_file: Path to coverage.toml. If None, looks for coverage.toml in repo root.

    Returns:
        Dictionary with coverage configuration, or empty dict if file not found.

    """
    if config_file is None:
        # Try to find coverage.toml in repo root
        repo_root = get_repo_root()
        config_file = repo_root / "coverage.toml"

    if not config_file.exists():
        return {"coverage": {"target": 90.0, "minimum": 80.0}}

    try:
        with open(config_file, "rb") as f:
            config = tomllib.load(f)
        return config
    except Exception as e:
        print(f"⚠️  Warning: Failed to load config from {config_file}: {e}", file=sys.stderr)
        return {"coverage": {"target": 90.0, "minimum": 80.0}}


def get_module_threshold(path: str, config: dict) -> float:
    """Get coverage threshold for a specific module.

    Args:
        path: Module path (e.g., "shared/core")
        config: Configuration dictionary from load_coverage_config()

    Returns:
        Minimum coverage threshold for the module.

    """
    modules = config.get("coverage", {}).get("modules", {})

    # Try exact match first
    if path in modules:
        return modules[path].get("minimum", 90.0)

    # Try prefix match
    for module_path in sorted(modules.keys(), key=len, reverse=True):
        if path.startswith(module_path):
            return modules[module_path].get("minimum", 90.0)

    # Default to overall minimum
    return config.get("coverage", {}).get("minimum", 80.0)


def parse_coverage_report(coverage_file: Path) -> float | None:
    """Parse coverage report and extract total coverage percentage.

    Parses Cobertura XML format (generated by pytest-cov).

    Args:
        coverage_file: Path to coverage.xml file

    Returns:
        Coverage percentage (0-100) or None if file not found/invalid

    """
    import defusedxml.ElementTree as ET  # noqa: N817

    if not coverage_file.exists():
        print(f"Coverage file not found: {coverage_file}", file=sys.stderr)
        return None

    try:
        tree = ET.parse(coverage_file)  # noqa: S314  # trusted source: pytest-cov generated file
        root = tree.getroot()

        # Cobertura format has line-rate attribute at root
        line_rate = root.get("line-rate")

        if line_rate is not None:
            # line-rate is a float from 0.0 to 1.0
            return float(line_rate) * 100.0
        else:
            print(f"Warning: No line-rate found in {coverage_file}", file=sys.stderr)
            return None

    except Exception as e:
        print(f"Error parsing coverage file: {e}", file=sys.stderr)
        return None
    print("   - No coverage report format to parse")
    print()
    print("   IMPACT: Coverage checks are skipped (better than fake passing)")
    print("   - No false sense of security from hardcoded mock values")
    print("   - CI still validates that tests execute successfully")
    print()
    print("   REFERENCE: ADR-008, Issue #2583, Issue #2612")
    print()
    print("   ➤ Returning None (coverage check disabled)")
    print()

    # Don't return fake value - return None to indicate not implemented
    # This way coverage checks are properly skipped rather than falsely passing
    return None


def check_coverage(threshold: float, path: str, coverage_file: Path) -> bool:
    """Check if coverage meets threshold.

    Args:
        threshold: Minimum required coverage percentage.
        path: Path to source code being tested.
        coverage_file: Path to coverage report.

    Returns:
        True if coverage meets threshold or coverage is not available,
        False only if coverage parsing succeeds but is below threshold.

    """
    coverage = parse_coverage_report(coverage_file)

    if coverage is None:
        print("\n📊 Coverage Report")
        print(f"   Path: {path}")
        print("   Status: Coverage parsing not implemented")
        print(f"   Threshold: {threshold:.2f}%")
        print()
        print("   ✅ PASSED - Coverage check skipped (tool not available)")
        print("      Tests are still validated for execution success")
        return True  # Pass gracefully when coverage is not available

    print("\n📊 Coverage Report")
    print(f"   Path: {path}")
    print(f"   Coverage: {coverage:.2f}%")
    print(f"   Threshold: {threshold:.2f}%")

    if coverage >= threshold:
        print("   ✅ PASSED - Coverage meets threshold")
        return True
    else:
        gap = threshold - coverage
        print(f"   ❌ FAILED - Coverage is {gap:.2f}% below threshold")
        return False


def main():
    """Run the coverage check script."""
    parser = argparse.ArgumentParser(description="Check test coverage against threshold")
    parser.add_argument(
        "--threshold",
        type=float,
        default=None,
        help="Minimum required coverage percentage (overrides config)",
    )
    parser.add_argument(
        "--path",
        type=str,
        default="shared/",
        help="Path to source code being tested (default: shared/)",
    )
    parser.add_argument(
        "--coverage-file",
        type=Path,
        default=Path("coverage.xml"),
        help="Path to coverage report file (default: coverage.xml)",
    )
    parser.add_argument(
        "--config",
        type=Path,
        default=None,
        help="Path to coverage.toml config file",
    )
    parser.add_argument("--verbose", action="store_true", help="Enable verbose output")

    args = parser.parse_args()

    # Load configuration
    config = load_coverage_config(args.config)

    # Determine threshold: use --threshold flag if provided, else get from config
    if args.threshold is not None:
        threshold = args.threshold
    else:
        threshold = get_module_threshold(args.path, config)

    if args.verbose:
        print("Checking coverage with settings:")
        print(f"  Threshold: {threshold}%")
        print(f"  Path: {args.path}")
        print(f"  Coverage file: {args.coverage_file}")
        print(f"  Config file: {args.config or 'default (coverage.toml)'}")

    # Check if coverage file exists
    if not args.coverage_file.exists():
        print(f"\n⚠️  WARNING: Coverage file not found: {args.coverage_file}", file=sys.stderr)
        print(
            "\n   Run tests with coverage first: pytest --cov=scylla --cov-report=xml",
            file=sys.stderr,
        )
        sys.exit(1)

    # Check coverage
    success = check_coverage(threshold, args.path, args.coverage_file)

    if not success:
        print("\n💡 Tips for improving coverage:")
        print("   - Add tests for uncovered functions")
        print("   - Test edge cases and error paths")
        print("   - Check for untested branches in conditionals")
        sys.exit(1)

    sys.exit(0)


if __name__ == "__main__":
    main()
